[package]
name = "hello"
version = "0.1.0"
edition.workspace = true

[dependencies]
env_logger.workspace=true
log.workspace=true
pollster.workspace=true
winit.workspace=true
wgpu.workspace=true


[[bin]]
name = "hello"
path = "src/main.rs"
