# Linux x86_64 专用配置
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+avx2,+fma"]

# Windows 专用配置
[target.x86_64-pc-windows-msvc]
# 明确禁用不兼容的指令集（避免在旧 CPU 崩溃）
# rustflags = [
#     "-C", "target-feature=+avx2,avx2,-avx512f",
#     "-C", "llvm-args=-x86-asm-syntax=intel"  # 可选：生成 Intel 风格汇编
# ]
rustflags = ["-C", "target-cpu=native"]
